<?php
// ============================================================================
// AI Chat Controller
// ============================================================================
// This is the API "door" 🚪 that the frontend chat widget knocks on.
// It receives the user's message, validates it, asks RestaurantAiChatService
// (the AI brain) for a reply, saves the conversation to the database,
// and sends the reply back to the user's screen.
//
// Route: POST /api/ai/chat
//
// Think of it as the waiter between the customer (frontend) and the kitchen (AI).
// ============================================================================

namespace App\Http\Controllers;

use App\Models\ChatLog;
use App\Services\RestaurantAiChatService;
use Illuminate\Http\Request;

class AiChatController extends Controller
{
    // __invoke endpoint that accepts a user message and an optional conversation history, and returns a reply generated by the RestaurantAiChatService. Validate the input data and return the generated reply in the response. If validation fails, return a 400 error with details about the validation errors. Handle any exceptions that may occur during the chat processing and return a 503 error with an appropriate message if the service is unavailable.
    public function __invoke(Request $request, RestaurantAiChatService $chatService)
    {
        // 1. Validate the incoming JSON (message + optional conversation history).
        $data = $request->validate([
            'message' => ['required', 'string', 'max:1000'],
            'history' => ['sometimes', 'array', 'max:20'],
            'history.*.role' => ['required_with:history', 'in:user,assistant'],
            'history.*.content' => ['required_with:history', 'string', 'max:4000'],
        ]);

        try {
            // 2. Hand the message to the AI brain (RestaurantAiChatService) and get a reply.
            $response = $chatService->reply(
                message: $data['message'],
                history: $data['history'] ?? [],
            );

            // 3. Save the conversation so the admin can review chat logs later.
            ChatLog::create([
                'question' => $data['message'],
                'response' => (string) ($response['reply'] ?? ''),
                'visitor_id' => $request->session()->get('visitor_id'),
                'created_at' => now(),
            ]);

            // 4. Send the reply back to the frontend chat widget.
            return response()->json($response);
        } catch (\Throwable $e) {
            // If the AI service is down or rate-limited, return a friendly error instead of crashing.
            report($e);
            $reply = $this->buildUserFacingErrorMessage($e);
            return response()->json([
                'reply' => $reply,
            ], 503);
        }
    }

    private function buildUserFacingErrorMessage(\Throwable $e): string
    {
        $defaultMessage = 'Sorry, I’m having trouble right now. Please try again in a moment.';
        $details = trim((string) $e->getMessage());

        if ($details === '') {
            return $defaultMessage;
        }

        $normalized = strtolower($details);
        $isRateLimited = str_contains($normalized, 'status 429')
            || str_contains($normalized, 'rate limit')
            || str_contains($normalized, 'too many requests');

        if (! $isRateLimited) {
            return $defaultMessage;
        }

        $retryAfterSeconds = $this->extractRetryAfterSeconds($details);
        $upgradeUrl = $this->extractUpgradeUrl($details);

        $message = 'Sorry, I’m having trouble right now.';
        if ($retryAfterSeconds !== null) {
            $message .= ' Please try again in '.$retryAfterSeconds.' seconds.';
        } else {
            $message .= ' Please try again in a moment.';
        }

        if ($upgradeUrl !== null) {
            $message .= ' Need more tokens? Upgrade here: '.$upgradeUrl;
        }

        return $message;
    }

    private function extractRetryAfterSeconds(string $details): ?int
    {
        if (preg_match('/please try again in\s*([0-9]+(?:\.[0-9]+)?)\s*s/i', $details, $matches) === 1) {
            return max(1, (int) ceil((float) $matches[1]));
        }

        if (preg_match('/retry[- ]?after\s*[:=]?\s*([0-9]+(?:\.[0-9]+)?)/i', $details, $matches) === 1) {
            return max(1, (int) ceil((float) $matches[1]));
        }

        return null;
    }

    private function extractUpgradeUrl(string $details): ?string
    {
        if (preg_match_all('/https?:\/\/[^\s)]+/i', $details, $matches) < 1) {
            return null;
        }

        $urls = array_map(
            static fn (string $url): string => rtrim($url, '.,;'),
            $matches[0]
        );

        foreach ($urls as $url) {
            $normalizedUrl = strtolower($url);
            if (str_contains($normalizedUrl, 'billing') || str_contains($normalizedUrl, 'upgrade')) {
                return $url;
            }
        }

        return $urls[0] ?? null;
    }
}
