<?php

namespace App\Http\Controllers;

use App\Models\ChatLog;
use App\Services\RestaurantAiChatService;
use Illuminate\Http\Request;

class AiChatController extends Controller
{
    // __invoke endpoint that accepts a user message and an optional conversation history, and returns a reply generated by the RestaurantAiChatService. Validate the input data and return the generated reply in the response. If validation fails, return a 400 error with details about the validation errors. Handle any exceptions that may occur during the chat processing and return a 503 error with an appropriate message if the service is unavailable.
    public function __invoke(Request $request, RestaurantAiChatService $chatService)
    {
        // Validate the input data
        $data = $request->validate([
            'message' => ['required', 'string', 'max:1000'],
            'history' => ['sometimes', 'array', 'max:20'],
            'history.*.role' => ['required_with:history', 'in:user,assistant'],
            'history.*.content' => ['required_with:history', 'string', 'max:1000'],
        ]);

        try {
            $response = $chatService->reply(
                message: $data['message'],
                history: $data['history'] ?? [],
            );

            ChatLog::create([
                'question' => $data['message'],
                'response' => (string) ($response['reply'] ?? ''),
                'visitor_id' => $request->session()->get('visitor_id'),
                'created_at' => now(),
            ]);

            return response()->json($response);
        } catch (\Throwable $e) {
            report($e);
            // Return a 503 error if the service is unavailable
            return response()->json([
                'reply' => 'Sorry, I’m having trouble right now. Please try again in a moment.',
            ], 503);
        }
    }
}
